---
certs:
  generate: true
  deploy: true
  group: foreman
katello: true
foreman: 
  organizations_enabled: true
  locations_enabled: true
  custom_repo: true
  ssl: true
  server_ssl_cert: /etc/pki/katello/certs/katello-apache.crt
  server_ssl_key: /etc/pki/katello/private/katello-apache.key
  server_ssl_ca: /etc/pki/katello/certs/katello-ca.crt
  server_ssl_chain: /etc/pki/katello/certs/katello-ca.crt
capsule:
  register_in_foreman: true
  puppet: true
  puppetca: true
