:mapping:
  :node_certs:
    :dir_name: 'kafo'
    :manifest_name: 'node_certs'

:no_prefix: true
:answer_file: /root/node-installer/config/answers.certs.yaml
:puppet_modules_dir: /root/node-installer/modules
