# kafo main configuration file example
# you can rename it to kafo.yaml so it overwrite default kafo settings
# note current configuration is written tokafo.yaml every time kafo is run

## Useful for development, e.g. when you want to move log files to local directory
# :log_dir: '/var/log/kafo'
# :log_level: :info

## Kafo tuning, customization of core functionality
# :no_prefix: false
# :mapping: {}
# :order:

## Advanced configuration - if not set it's ignored
# :log_owner: root
# :log_group: root

:mapping:
  :node_certs:
    :dir_name: 'kafo'
    :manifest_name: 'node_certs'

:no_prefix: true
:answer_file: /root/node-installer/config/answers.certs.yaml
:puppet_modules_dir: /root/node-installer/modules
